### ISSUE TITLE
使用时出现TimeoutError的警告

### ISSUE THREAD

**Issue by DMB-codegang** [araea/koishi-plugin-markdown-to-image-service#2]
```
command markdowntoimage ＃主标题h1
                        TimeoutError: Navigation timeout of 30000 ms exceeded
                            at new Deferred (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
                            at Deferred.create (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
                            at new LifecycleWatcher (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
                            at CdpFrame.goto (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:151:29)
                            at CdpFrame.<anonymous> (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
                            at CdpPage.goto (/koishi/node_modules/koishi-plugin-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:588:43)
                            at MarkdownToImageService.generateAndSaveImage (/koishi/node_modules/koishi-plugin-markdown-to-image-service/lib/index.js:593:16)
                            at async MarkdownToImageService.convertToImage (/koishi/node_modules/koishi-plugin-markdown-to-image-service/lib/index.js:614:14)
                            at async _Command.<anonymous> (/koishi/node_modules/koishi-plugin-markdown-to-image-service/lib/index.js:633:27)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1078:14)
```

**Comment by araea** [comment]
`pptr` 插件出了问题，重启 `pptr` 服务即可。

**Comment by DMB-codegang** [comment]
我将`koishi-plugin-puppeteer`升级到了3.9.0，并尝试过了重启`koishi-plugin-puppeteer`和`koishi`，但报错依旧
![image](https://github.com/user-attachments/assets/68248a2b-1f74-4bdd-b359-9dd08b1d822f)

**Comment by araea** [comment]
初步分析后，我认为原因可能如下：

> 程序运行的用户没有在目标目录下创建文件的权限，导致 HTML 文件无法被创建，由于 HTML 文件不存在，`page.goto()` 方法无法导航到该文件，最终导致超时错误。

**Comment by DMB-codegang** [comment]
我是用docker运行的koishi，会和这个有关系吗
如果真的是因为用户权限问题，那么应该如何解决呢

**Comment by araea** [comment]
我使用 Docker 新建 Koishi 实例，通过小火箭更新依赖。

安装本插件且配置好 `pptr` 服务后启动插件，沙盒中可正常使用，如下图：

![image](https://github.com/user-attachments/assets/99c1c462-afbe-4f18-9a53-38290bf98f36)


我无法复现问题。

**Comment by DMB-codegang** [comment]
问题解决，方式：指定容器DNS
